<Project>
    <PropertyGroup>
        <TargetFramework>net11.0</TargetFramework>
        <EnablePreviewFeatures>true</EnablePreviewFeatures>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <WarningsAsErrors>nullable</WarningsAsErrors>
    </PropertyGroup>
</Project>